# Generated by Django 3.1 on 2021-12-22 17:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_auto_20211222_1843'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderproduct',
            old_name='product_variations',
            new_name='product_variation',
        ),
    ]
